
#
# Hello world Waf script
#
from __future__ import print_function

rtems_version = "6"

try:
    import rtems_waf.rtems as rtems
except:
    print('error: no rtems_waf git submodule')
    import sys
    sys.exit(1)

def init(ctx):
    rtems.init(ctx, version = rtems_version, long_commands = True)

def bsp_configure(conf, arch_bsp):
    # Add BSP specific configuration checks
    pass

def options(opt):
    rtems.options(opt)

def configure(conf):
    conf.env.LIB_zenohpico = ['zenohpico', 'bsd', 'm']
    conf.env.INCLUDES_zenohpico = ['/root/zenoh-pico/include']
    conf.env.LIBPATH_zenohpico = ['/root/zenoh-pico/build/lib']
    conf.env.DEFINES_zenohpico = ['ZENOH_BSD=1']
    rtems.configure(conf, bsp_configure=bsp_configure)

def build(bld):
    rtems.build(bld)
    bld(features = 'c cprogram',
        target = 'hello_zenoh.exe',
        cflags = '-g',
        #includes = 'foo',
        #lib = ['bsd', 'm'],
        use = ['zenohpico'],
        source = ['hello.c',
                  'init.c'])
